services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "8081:8081"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml